# 公共配置文件
server:
  port: 8090
spring:
  cloud:
    gateway:
      default-filters:
        - AddResponseHeader=source, doupi
      routes:
        - id: api_route
          uri: http://localhost:8123
          predicates:
            - Path=/api/**

logging:
  level:
    org:
      springframework:
        cloud:
          gateway: trace



  application:
    name: douapigateway-consumer  # 服务消费者的应用名

dubbo:
  application:
    name: ${spring.application.name}
  registry:
    address: nacos://localhost:8848  # Nacos注册中心地址
  consumer:
    check: false  # 消费者检查禁用，如果是开发环境可以设置为true



